<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">

<!-- Begin Jekyll SEO tag v2.5.0 -->
<title>Welcome | Hello, World!</title>
<meta name="generator" content="Jekyll v3.8.5" />
<meta property="og:title" content="Welcome" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="Creating a Web Page!" />
<meta property="og:description" content="Creating a Web Page!" />
<link rel="canonical" href="https://aiyanavezoli.github.io/Project0/" />
<meta property="og:url" content="https://aiyanavezoli.github.io/Project0/" />
<meta property="og:site_name" content="Project0" />
<script type="application/ld+json">
{"@type":"WebSite","headline":"Welcome","url":"https://aiyanavezoli.github.io/Project0/","name":"Project0","description":"Creating a Web Page!","@context":"http://schema.org"}</script>
<!-- End Jekyll SEO tag -->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#142626">
    <link rel="stylesheet" href="/Project0/assets/css/style.css?v=b7ecc988d59d2d30548534a4ed9463bb7d35ebc3">
  </head>
  <body>
    <section class="page-header">
      <h1 class="project-name">Hello, World!</h1>
      <h2 class="project-tagline">Creating a Web Page!</h2>
      
        <a href="https://github.com/Aiyanavezoli/Project0" class="btn">View on GitHub</a>
